"""
为 RemDet（mmyolo）和 DEIM 生成训练配置：继承各自官方配置，只改数据、轮数、batch、
随机种子，以及官方规定的"改 batch 时要跟着改"的量。其余一律用官方值。

改 batch 的规则都来自官方：
  * RemDet-Tiny 官方是 8 卡 x 32 = 256。mmdet 自带的 auto_scale_lr（线性缩放）
    按 base_batch_size=256 把学习率缩到实际 batch。
  * DEIM-N 官方总 batch 32。DEIM README "Customizing Batch Size" 规定：学习率按线性缩放，
    EMA decay 按 1 - (1 - decay) * k，EMA 和学习率的预热步数按 1 / k 缩放（k = 新 batch / 32）。
"""
from __future__ import annotations

from pathlib import Path


def _p(path) -> str:
    return Path(path).as_posix()


def _num(x: float) -> str:
    """A float YAML reads as a float: YAML 1.1 parses '5e-05' (no dot) as a string."""
    s = f"{x:.12f}".rstrip("0")
    return s + "0" if s.endswith(".") else s


def remdet_config(remdet_dir, out_cfg, work_dir, paths: dict, epochs: int, batch: int,
                  workers: int, seed: int, close_mosaic: int = 10) -> Path:
    """RemDet-Tiny on VisDrone. Inherits config_remdet/remdet/remdet_tiny-300e_coco.py
    (which itself inherits the official VisDrone config remdet_s-300e_visdrone.py)."""
    base = _p(Path(remdet_dir).resolve() / "config_remdet" / "remdet" / "remdet_tiny-300e_coco.py")
    text = f'''# Generated by baselines/train_baselines.py -- edit that script, not this file.
_base_ = '{base}'

max_epochs = {epochs}
close_mosaic_epochs = {close_mosaic}
train_batch_size_per_gpu = {batch}
train_num_workers = {workers}
work_dir = '{_p(work_dir)}'
randomness = dict(seed={seed})

# RemDet-Tiny's official batch is 8 GPUs x 32; mmdet's linear LR scaling rule
auto_scale_lr = dict(enable=True, base_batch_size=256)

train_dataloader = dict(
    batch_size=train_batch_size_per_gpu,
    num_workers=train_num_workers,
    dataset=dict(data_root='', ann_file='{_p(paths["train_coco"])}',
                 data_prefix=dict(img='{_p(paths["train_images"])}/')))
val_dataloader = dict(
    num_workers=train_num_workers,
    dataset=dict(data_root='', ann_file='{_p(paths["val_coco"])}',
                 data_prefix=dict(img='{_p(paths["val_images"])}/')))
test_dataloader = val_dataloader
val_evaluator = dict(ann_file='{_p(paths["val_coco"])}')
test_evaluator = val_evaluator

optim_wrapper = dict(optimizer=dict(batch_size_per_gpu=train_batch_size_per_gpu))
default_hooks = dict(param_scheduler=dict(max_epochs=max_epochs))
custom_hooks = [
    dict(type='EMAHook', ema_type='ExpMomentumEMA', momentum=0.0001,
         update_buffers=True, strict_load=False, priority=49),
    dict(type='mmdet.PipelineSwitchHook', switch_epoch=max_epochs - close_mosaic_epochs,
         switch_pipeline=_base_.train_pipeline_stage2),
]
train_cfg = dict(max_epochs=max_epochs,
                 dynamic_intervals=[(max_epochs - close_mosaic_epochs, _base_.val_interval_stage2)])
'''
    out_cfg = Path(out_cfg)
    out_cfg.parent.mkdir(parents=True, exist_ok=True)
    out_cfg.write_text(text, encoding="utf-8")
    return out_cfg


# DEIM-N's official values (configs/deim_dfine/deim_hgnetv2_n_coco.yml, configs/base/*.yml)
DEIM_N = dict(batch=32, lr=0.0008, backbone_lr=0.0004, weight_decay=0.0001,
              ema_decay=0.9999, ema_warmups=1000, warmup_iter=2000, no_aug_epoch=12,
              first_aug_epoch=4)


def deim_schedule(epochs: int) -> dict:
    """DEIM-N's epoch milestones for a different length, kept in the official
    proportions: 160 = 148 + 12 -> policy [4, 4 + 148 // 2, 148], mixup [4, 78]."""
    stop = epochs - DEIM_N["no_aug_epoch"]
    mid = DEIM_N["first_aug_epoch"] + stop // 2
    return {"stop": stop, "policy": [DEIM_N["first_aug_epoch"], mid, stop],
            "mixup": [DEIM_N["first_aug_epoch"], mid]}


def deim_config(deim_dir, out_cfg, out_dir, paths: dict, epochs: int, batch: int,
                workers: int, pretrained_dir=None, num_classes: int = 10) -> Path:
    base = _p(Path(deim_dir).resolve() / "configs" / "deim_dfine" / "deim_hgnetv2_n_coco.yml")
    k = batch / DEIM_N["batch"]
    s = deim_schedule(epochs)
    # the official ImageNet-pretrained HGNetv2-B0 is downloaded here on first use
    # (DEIM's default is a path relative to the working directory)
    pre = _p(pretrained_dir or Path(out_dir).parent / "pretrained" / "hgnetv2") + "/"
    text = f'''# Generated by baselines/train_baselines.py -- edit that script, not this file.
__include__: ['{base}']

output_dir: '{_p(out_dir)}'
num_classes: {num_classes}
remap_mscoco_category: False
epoches: {epochs}
no_aug_epoch: {DEIM_N["no_aug_epoch"]}

HGNetv2:
  local_model_dir: '{pre}'

train_dataloader:
  total_batch_size: {batch}
  num_workers: {workers}
  dataset:
    img_folder: '{_p(paths["train_images"])}'
    ann_file: '{_p(paths["train_coco"])}'
    transforms:
      policy:
        epoch: {s["policy"]}
  collate_fn:
    mixup_epochs: {s["mixup"]}
    stop_epoch: {s["stop"]}

val_dataloader:
  num_workers: {workers}
  dataset:
    img_folder: '{_p(paths["val_images"])}'
    ann_file: '{_p(paths["val_coco"])}'

# DEIM README "Customizing Batch Size": linear LR scaling, EMA decay 1 - (1 - d) * k,
# warmups / k, with k = {batch} / {DEIM_N["batch"]}
optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: {_num(DEIM_N["backbone_lr"] * k)}
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: {_num(DEIM_N["backbone_lr"] * k)}
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.
  lr: {_num(DEIM_N["lr"] * k)}
  betas: [0.9, 0.999]
  weight_decay: {_num(DEIM_N["weight_decay"])}

ema:
  decay: {_num(1 - (1 - DEIM_N["ema_decay"]) * k)}
  warmups: {round(DEIM_N["ema_warmups"] / k)}

warmup_iter: {round(DEIM_N["warmup_iter"] / k)}
'''
    out_cfg = Path(out_cfg)
    out_cfg.parent.mkdir(parents=True, exist_ok=True)
    out_cfg.write_text(text, encoding="utf-8")
    return out_cfg
